//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamPerfomanceTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamFeedback
    {
        public int TeamFeedbackID { get; set; }
        public Nullable<int> ContributionScore { get; set; }
        public Nullable<int> GroupWorkScore { get; set; }
        public Nullable<int> HappinessScore { get; set; }
        public Nullable<int> PrideScore { get; set; }
        public Nullable<int> SatisfactionScore { get; set; }
    }
}
